### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by petelah** [petelah/snake#1]
Quick fixes:

- [x] Make snake die when hits itself
- [ ] Add background music
- [x] Add collision sfx
- [ ] Add toggle music on/off key
- [x] Add high scores to menu
- [ ] Update level function

Future big ideas:

- [ ] Add tensor flow solving algo
- [ ] Add controller support
- [ ] Allow user to change directional keys to preference
- [ ] Port to stand alone exe and mac app
